service: slsproj

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  hello:
    handler: main.handler
    events:
      - http:
          path: hello
          method: post
